/**
 * Per-faction building definitions. Every faction defines exactly the same
 * four canonical roles (main structure, resource dropoff, basic production,
 * heavy production) - the only building types the engine actually
 * implements (no auto-attacking defense-tower/research/teleport systems
 * exist yet). Engine code (PlayerBase, AIController) addresses buildings by
 * role, never by a faction-specific id, so it never needs to know which
 * faction it's running.
 *
 * Names/ids/colors follow the detailed per-faction building catalog
 * (Nexus Core, Cyber-Forge, EMP Arc Turret, ...). Each faction's catalog
 * lists three buildings (Command Center / Factory / Defense Tower) - since
 * the engine has no tower-combat system, the "tower" entry is repurposed
 * here as the heavyProduction role (its striking silhouette carries over,
 * its auto-attack ability doesn't). resourceDropoff isn't in that catalog
 * at all, so it keeps its original name/visual.
 */
export type BuildingRole = 'main' | 'resourceDropoff' | 'basicProduction' | 'heavyProduction';
export const BUILDING_ROLES: BuildingRole[] = ['main', 'resourceDropoff', 'basicProduction', 'heavyProduction'];

export interface BuildingConfig {
  id: string;
  name: string;
  costCoreEnergy: number;
  costFactionResource: number;
  buildTimeSec: number;
  /** Placeholder footprint radius for the placeholder mesh/placement radius. */
  footprint: number;
  /** Engine-only vision/HP stats, not part of the design doc's cost tables. */
  visionRadius: number;
  maxHp: number;
  color: number;
  /** Material family per the faction's visual style (chrome/basalt/gold/riveted-steel). */
  materialRoughness: number;
  materialMetalness: number;
  /** Unit ids this building can produce. Empty = no production. */
  produces: string[];
  /** Which resource harvesters deposit here, if any. */
  dropoffResource: 'coreEnergy' | 'factionResource' | null;
}

export const BUILDINGS_BY_FACTION: Record<string, Record<BuildingRole, BuildingConfig>> = {
  'cyber-nexus': {
    main: {
      id: 'nexus-core',
      name: 'Nexus Core',
      costCoreEnergy: 0,
      costFactionResource: 400,
      buildTimeSec: 90,
      footprint: 3,
      visionRadius: 16,
      maxHp: 800,
      color: 0x9fd8ff,
      materialRoughness: 0.15,
      materialMetalness: 0.9,
      produces: ['flux-harvester'],
      dropoffResource: 'coreEnergy',
    },
    resourceDropoff: {
      id: 'flux-siphon',
      name: 'Flux Siphon',
      costCoreEnergy: 50,
      costFactionResource: 0,
      buildTimeSec: 25,
      footprint: 2,
      visionRadius: 10,
      maxHp: 200,
      color: 0x2ea3ff,
      materialRoughness: 0.15,
      materialMetalness: 0.9,
      produces: [],
      dropoffResource: 'factionResource',
    },
    basicProduction: {
      id: 'cyber-forge',
      name: 'Cyber-Forge',
      costCoreEnergy: 100,
      costFactionResource: 100,
      buildTimeSec: 35,
      footprint: 2.5,
      visionRadius: 10,
      maxHp: 250,
      color: 0x3fb0ff,
      materialRoughness: 0.15,
      materialMetalness: 0.9,
      produces: ['nexus-striker', 'nanite-weaver'],
      dropoffResource: null,
    },
    heavyProduction: {
      id: 'emp-arc-turret',
      name: 'EMP Arc Turret',
      costCoreEnergy: 150,
      costFactionResource: 150,
      buildTimeSec: 45,
      footprint: 3,
      visionRadius: 10,
      maxHp: 300,
      color: 0x1f7fcc,
      materialRoughness: 0.15,
      materialMetalness: 0.9,
      produces: ['tesla-archon'],
      dropoffResource: null,
    },
  },

  pyroliths: {
    main: {
      id: 'magma-hearth',
      name: 'Magma Hearth',
      costCoreEnergy: 0,
      costFactionResource: 400,
      buildTimeSec: 90,
      footprint: 3.2,
      visionRadius: 15,
      maxHp: 900,
      color: 0xff6a1a,
      materialRoughness: 0.9,
      materialMetalness: 0.05,
      produces: ['cinder-grub'],
      dropoffResource: 'coreEnergy',
    },
    resourceDropoff: {
      id: 'ember-well',
      name: 'Ember Well',
      costCoreEnergy: 50,
      costFactionResource: 0,
      buildTimeSec: 25,
      footprint: 2,
      visionRadius: 9,
      maxHp: 220,
      color: 0xff8c42,
      materialRoughness: 0.9,
      materialMetalness: 0.05,
      produces: [],
      dropoffResource: 'factionResource',
    },
    basicProduction: {
      id: 'spawning-pit',
      name: 'Spawning Pit',
      costCoreEnergy: 100,
      costFactionResource: 100,
      buildTimeSec: 35,
      footprint: 2.5,
      visionRadius: 9,
      maxHp: 280,
      color: 0xcc4a10,
      materialRoughness: 0.9,
      materialMetalness: 0.05,
      produces: ['magma-imp', 'ignis-priest'],
      dropoffResource: null,
    },
    heavyProduction: {
      id: 'volcanic-spire',
      name: 'Volcanic Spire',
      costCoreEnergy: 150,
      costFactionResource: 150,
      buildTimeSec: 45,
      footprint: 3.2,
      visionRadius: 9,
      maxHp: 340,
      color: 0x8a2f10,
      materialRoughness: 0.9,
      materialMetalness: 0.05,
      produces: ['acid-drake'],
      dropoffResource: null,
    },
  },

  'solari-archons': {
    main: {
      id: 'sanctum-of-light',
      name: 'Sanctum of Light',
      costCoreEnergy: 0,
      costFactionResource: 400,
      buildTimeSec: 90,
      footprint: 3,
      visionRadius: 18,
      maxHp: 650,
      color: 0xf4c542,
      materialRoughness: 0.25,
      materialMetalness: 0.6,
      produces: [],
      dropoffResource: 'coreEnergy',
    },
    resourceDropoff: {
      id: 'radiant-well',
      name: 'Radiant Well',
      costCoreEnergy: 50,
      costFactionResource: 0,
      buildTimeSec: 25,
      footprint: 2,
      visionRadius: 12,
      maxHp: 160,
      color: 0xffe08a,
      materialRoughness: 0.25,
      materialMetalness: 0.6,
      produces: [],
      dropoffResource: null,
    },
    basicProduction: {
      id: 'celestial-spire',
      name: 'Celestial Spire',
      costCoreEnergy: 100,
      costFactionResource: 100,
      buildTimeSec: 35,
      footprint: 2.5,
      visionRadius: 12,
      maxHp: 200,
      color: 0xd9a834,
      materialRoughness: 0.25,
      materialMetalness: 0.6,
      produces: ['solar-zealot', 'astral-frost-scribe'],
      dropoffResource: null,
    },
    heavyProduction: {
      id: 'prism-obelisk',
      name: 'Prism Obelisk',
      costCoreEnergy: 150,
      costFactionResource: 150,
      buildTimeSec: 45,
      footprint: 3,
      visionRadius: 12,
      maxHp: 230,
      color: 0x9b5de5,
      materialRoughness: 0.25,
      materialMetalness: 0.6,
      produces: ['void-arbiter'],
      dropoffResource: null,
    },
  },

  'frost-forged': {
    main: {
      id: 'iron-foundry',
      name: 'Iron Foundry',
      costCoreEnergy: 0,
      costFactionResource: 400,
      buildTimeSec: 90,
      footprint: 3.2,
      visionRadius: 15,
      maxHp: 950,
      color: 0xb5651d,
      materialRoughness: 0.55,
      materialMetalness: 0.55,
      produces: ['rustling'],
      dropoffResource: 'coreEnergy',
    },
    resourceDropoff: {
      id: 'coal-depot',
      name: 'Coal Depot',
      costCoreEnergy: 50,
      costFactionResource: 0,
      buildTimeSec: 25,
      footprint: 2,
      visionRadius: 9,
      maxHp: 240,
      color: 0x8a4a17,
      materialRoughness: 0.55,
      materialMetalness: 0.55,
      produces: [],
      dropoffResource: 'factionResource',
    },
    basicProduction: {
      id: 'steam-works',
      name: 'Steam Works',
      costCoreEnergy: 100,
      costFactionResource: 100,
      buildTimeSec: 35,
      footprint: 2.5,
      visionRadius: 9,
      maxHp: 320,
      color: 0x6f7a80,
      materialRoughness: 0.55,
      materialMetalness: 0.55,
      produces: ['steam-scrapper', 'cryo-thrower-mech'],
      dropoffResource: null,
    },
    heavyProduction: {
      id: 'mortar-bunker',
      name: 'Mortar Bunker',
      costCoreEnergy: 150,
      costFactionResource: 150,
      buildTimeSec: 45,
      footprint: 3.2,
      visionRadius: 9,
      maxHp: 380,
      color: 0x4fd8e0,
      materialRoughness: 0.55,
      materialMetalness: 0.55,
      produces: ['boiler-juggernaut'],
      dropoffResource: null,
    },
  },

  'verdant-wilds': {
    main: {
      id: 'heartroot',
      name: 'Heartroot',
      costCoreEnergy: 0,
      costFactionResource: 400,
      buildTimeSec: 90,
      footprint: 3.1,
      visionRadius: 15,
      maxHp: 850,
      color: 0x4a8f3d,
      materialRoughness: 0.8,
      materialMetalness: 0.05,
      produces: ['root-tender'],
      dropoffResource: 'coreEnergy',
    },
    resourceDropoff: {
      id: 'marrow-nest',
      name: 'Marrow Nest',
      costCoreEnergy: 50,
      costFactionResource: 0,
      buildTimeSec: 25,
      footprint: 2,
      visionRadius: 9,
      maxHp: 200,
      color: 0x7fb356,
      materialRoughness: 0.8,
      materialMetalness: 0.05,
      produces: [],
      dropoffResource: 'factionResource',
    },
    basicProduction: {
      id: 'spawning-bog',
      name: 'Spawning Bog',
      costCoreEnergy: 100,
      costFactionResource: 100,
      buildTimeSec: 35,
      footprint: 2.5,
      visionRadius: 9,
      maxHp: 260,
      color: 0x3a6b2e,
      materialRoughness: 0.8,
      materialMetalness: 0.05,
      produces: ['thorn-skitterling', 'spore-mystic'],
      dropoffResource: null,
    },
    heavyProduction: {
      id: 'bramble-maw',
      name: 'Bramble Maw',
      costCoreEnergy: 150,
      costFactionResource: 150,
      buildTimeSec: 45,
      footprint: 3.1,
      visionRadius: 9,
      maxHp: 310,
      color: 0x2a4d20,
      materialRoughness: 0.8,
      materialMetalness: 0.05,
      produces: ['bramble-colossus'],
      dropoffResource: null,
    },
  },

  'umbral-voidkin': {
    main: {
      id: 'rift-spire',
      name: 'Rift Spire',
      costCoreEnergy: 0,
      costFactionResource: 400,
      buildTimeSec: 90,
      footprint: 3,
      visionRadius: 17,
      maxHp: 700,
      color: 0x6a2fa0,
      materialRoughness: 0.2,
      materialMetalness: 0.3,
      produces: ['husk-drifter'],
      dropoffResource: 'coreEnergy',
    },
    resourceDropoff: {
      id: 'ichor-well',
      name: 'Ichor Well',
      costCoreEnergy: 50,
      costFactionResource: 0,
      buildTimeSec: 25,
      footprint: 2,
      visionRadius: 11,
      maxHp: 180,
      color: 0x8a4fc0,
      materialRoughness: 0.2,
      materialMetalness: 0.3,
      produces: [],
      dropoffResource: 'factionResource',
    },
    basicProduction: {
      id: 'wraith-cradle',
      name: 'Wraith Cradle',
      costCoreEnergy: 100,
      costFactionResource: 100,
      buildTimeSec: 35,
      footprint: 2.5,
      visionRadius: 10,
      maxHp: 220,
      color: 0x4a1f70,
      materialRoughness: 0.2,
      materialMetalness: 0.3,
      produces: ['shade-stalker', 'nullweaver'],
      dropoffResource: null,
    },
    heavyProduction: {
      id: 'maw-of-the-void',
      name: 'Maw of the Void',
      costCoreEnergy: 150,
      costFactionResource: 150,
      buildTimeSec: 45,
      footprint: 3,
      visionRadius: 11,
      maxHp: 280,
      color: 0x2d0f4a,
      materialRoughness: 0.2,
      materialMetalness: 0.3,
      produces: ['voidmaw-horror'],
      dropoffResource: null,
    },
  },
};

/** Flat id-keyed view for Cyber-Nexus, kept for the player-facing UI which always plays Cyber-Nexus. */
export const CYBER_NEXUS_BUILDINGS: Record<string, BuildingConfig> = Object.fromEntries(
  BUILDING_ROLES.map((role) => [BUILDINGS_BY_FACTION['cyber-nexus'][role].id, BUILDINGS_BY_FACTION['cyber-nexus'][role]]),
);

/** Building id -> canonical role, for picking a building's procedural visual archetype (buildingVisuals.ts) from any faction's config. */
export const BUILDING_ROLE_BY_ID: Record<string, BuildingRole> = Object.fromEntries(
  Object.values(BUILDINGS_BY_FACTION).flatMap((byRole) => BUILDING_ROLES.map((role) => [byRole[role].id, role] as const)),
);
